=== NNemanjaMM/EDS/TAS-Solution/src/main/resources/com/tas/xml/vulnerabilities/VulnerabilitiesSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ts="https://www.tas.org/tas-schemas"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    targetNamespace="https://www.tas.org/tas-schemas" elementFormDefault="qualified"
    vc:minVersion="1.1">
    <xs:element name="vulnerabilitiesDefinitions">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="vulnerabilityDefinition"
                    type="ts:vulnerabilityDefinition"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="vulnerabilityDefinition">
        <xs:sequence>
            <xs:element name="description" type="ts:stringAndLink"/>
            <xs:element name="countermeasures" type="ts:stringAndLink"/>
        </xs:sequence>
        <xs:attribute name="vulnerabilityId" type="xs:ID" use="required"/>
        <xs:attribute name="vulnerabilityTitle" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="stringAndLink">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="link">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="address" type="xs:anyURI" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== NNemanjaMM/EDS/TAS-Solution/src/main/resources/com/tas/xml/vulnerabilities/vulnerabilities_definitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<vulnerabilitiesDefinitions xmlns="https://www.tas.org/tas-schemas"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.tas.org/tas-schemas file:/D:/Master/work/TAS/TAS-Solution/src/main/resources/com/tas/xml/vulnerabilities/VulnerabilitiesSchema.xsd">
    
    <vulnerabilityDefinition
        vulnerabilityId="vd00000001" 
        vulnerabilityTitle="Injection">
        <description></description>
        <countermeasures></countermeasures>
    </vulnerabilityDefinition>
    
    <vulnerabilityDefinition 
        vulnerabilityId="vd00000002" 
        vulnerabilityTitle="Identity Spoofing">
        <description></description>
        <countermeasures></countermeasures>
    </vulnerabilityDefinition>
    
    <vulnerabilityDefinition 
        vulnerabilityId="vd00000003" 
        vulnerabilityTitle="Program Spoofing">
        <description></description>
        <countermeasures></countermeasures>
    </vulnerabilityDefinition>
    
</vulnerabilitiesDefinitions>
