=== NNemanjaMM/EDS/TAS-Solution/resources/schemas/ExploitsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ts="https://www.tas.org/tas-schemas"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    targetNamespace="https://www.tas.org/tas-schemas" elementFormDefault="qualified"
    vc:minVersion="1.1">
    <xs:include schemaLocation="AssetSchema.xsd"/>
    <xs:element name="exploitDefinitions">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="exploitDefinition"
                    type="ts:exploitDefinition"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="exploitDefinition">
        <xs:sequence>
            <xs:element name="description" type="ts:stringAndLink"/>
            <xs:element name="countermeasures" type="ts:stringAndLink"/>
        </xs:sequence>
        <xs:attribute name="exploitId" type="xs:ID" use="required"/>
        <xs:attribute name="exploitTitle" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="exploitDefinitionReport">
        <xs:sequence>
            <xs:element name="endangeredAsset" type="ts:assetDefinition"/>
            <xs:element name="description" type="ts:stringAndLink"/>
            <xs:element name="countermeasures" type="ts:stringAndLink"/>
        </xs:sequence>
        <xs:attribute name="exploitId" type="xs:ID" use="required"/>
        <xs:attribute name="exploitTitle" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="stringAndLink">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="link">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="address" type="xs:anyURI" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== NNemanjaMM/EDS/TAS-Solution/src/main/resources/com/tas/xml/exploits/exploits_definitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<exploitDefinitions xmlns="https://www.tas.org/tas-schemas"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.tas.org/tas-schemas file:/D:/Master/work/TAS/TAS-Solution/src/main/resources/com/tas/xml/exploits/ExploitsSchema.xsd">
    
    <exploitDefinition
        exploitId="vd00000001" 
        exploitTitle="SQL Injection">
        <description></description>
        <countermeasures></countermeasures>
    </exploitDefinition>
    
    <exploitDefinition 
        exploitId="vd00000002" 
        exploitTitle="XML Injection">
        <description>Some description for XML Injection</description>
        <countermeasures>There are a lots of them...</countermeasures>
    </exploitDefinition>
    
    <exploitDefinition 
        exploitId="vd00000003" 
        exploitTitle="Cross-Site Scripting">
        <description></description>
        <countermeasures></countermeasures>
    </exploitDefinition>
    
    <exploitDefinition 
        exploitId="vd00000004" 
        exploitTitle="Cross-Site Request Forgey">
        <description></description>
        <countermeasures></countermeasures>
    </exploitDefinition>
    
    <exploitDefinition 
        exploitId="vd00000005" 
        exploitTitle="Sniffing">
        <description></description>
        <countermeasures></countermeasures>
    </exploitDefinition>
    
    <exploitDefinition 
        exploitId="vd00000006" 
        exploitTitle="Session Hijack">
        <description></description>
        <countermeasures></countermeasures>
    </exploitDefinition>
    
    <exploitDefinition 
        exploitId="vd00000007" 
        exploitTitle="Elevation of Privilege">
        <description></description>
        <countermeasures></countermeasures>
    </exploitDefinition>
    
</exploitDefinitions>
