=== NNemanjaMM/EDS/TAS-Solution/src/main/resources/com/tas/xml/threats/ThreatSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1" targetNamespace="https://www.tas.org/tas-schemas"
    xmlns:ts="https://www.tas.org/tas-schemas">
    <xs:complexType name="elementsListType">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="element" type="ts:elementType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="assetsListType">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="asset" type="ts:assetType">
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="threatsListType">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="threat" type="ts:threatType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="threatDefinitionsType">
        <xs:sequence>
            <xs:element name="threatDefinition" type="ts:threatDefinitionType" maxOccurs="unbounded"
            />
        </xs:sequence>
    </xs:complexType>
    <xs:element name="definitions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="elementsList" type="ts:elementsListType"/>
                <xs:element name="assetsList" type="ts:assetsListType"/>
                <xs:element name="threatsList" type="ts:threatsListType"/>
                <xs:element name="threatDefinitions" type="ts:threatDefinitionsType"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="elementKey">
            <xs:selector xpath="ts:elementsList/ts:element"/>
            <xs:field xpath="@elementId"/>
        </xs:key>
        <xs:key name="assetKey">
            <xs:selector xpath="ts:assetsList/ts:asset"/>
            <xs:field xpath="@assetId"/>
        </xs:key>
        <xs:key name="threatKey">
            <xs:selector xpath="ts:threatsList/ts:threat"/>
            <xs:field xpath="@threatId"/>
        </xs:key>
        <xs:keyref name="elemenKeyRef" refer="ts:elementKey">
            <xs:selector xpath="ts:threatDefinitions/ts:threatDefinition/ts:requirements"/>
            <xs:field xpath="@elementId"/>
        </xs:keyref>
        <xs:keyref name="assetKeyRef" refer="ts:assetKey">
            <xs:selector xpath="ts:threatDefinitions/ts:threatDefinition/ts:requirements"/>
            <xs:field xpath="@assetId"/>
        </xs:keyref>
        <xs:keyref name="threatKeyRef" refer="ts:threatKey">
            <xs:selector xpath="ts:threatDefinitions/ts:threatDefinition/ts:threats/ts:threat"/>
            <xs:field xpath="@threatId"/>
        </xs:keyref>
    </xs:element>
    <xs:complexType name="elementType">
        <xs:attribute name="elementId" type="xs:ID" use="required"/>
        <xs:attribute name="title" type="xs:string"/>
        <xs:attribute name="elementName" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:whiteSpace value="collapse"/>
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="assetType">
        <xs:attribute name="assetId" type="xs:ID" use="required"/>
        <xs:attribute name="assetName" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="threatType">
        <xs:attribute name="threatId" type="xs:ID" use="required"/>
        <xs:attribute name="threatName" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="threatDefinitionType">
        <xs:sequence>
            <xs:element name="requirements">
                <xs:complexType>
                    <xs:attribute name="assetId" type="xs:IDREF" use="required"/>
                    <xs:attribute default="false" name="endangersConfidentiality" type="xs:boolean"/>
                    <xs:attribute default="false" name="endangersIntegrity" type="xs:boolean"/>
                    <xs:attribute default="false" name="endangersAvailability" type="xs:boolean"/>
                    <xs:attribute name="elementId" type="xs:IDREF" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="threats">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="threat" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:attribute name="threatId" type="xs:IDREF" use="required"/>
                                <xs:attribute name="severity">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:int">
                                            <xs:minInclusive value="1"/>
                                            <xs:maxInclusive value="5"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
</xs:schema>

=== NNemanjaMM/EDS/TAS-Solution/src/main/resources/com/tas/xml/threats/threat_definitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="https://www.tas.org/tas-schemas"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.tas.org/tas-schemas file:/D:/Master/work/TAS/TAS-Solution/src/main/resources/com/tas/xml/threats/ThreatSchema.xsd">
    <elementsList>
        <element title="SQL Database" elementId="el00000001" elementName="sqlDatabase" />
        <element title="Web Application" elementId="el00000002" elementName="webApplication" />
    </elementsList>
    
    <assetsList>
        <asset assetName="Password" assetId="al00000001" />
    </assetsList>
    
    <threatsList>
        <threat threatName="DOS" threatId="tl00000001"/>
    </threatsList>
    
    <threatDefinitions>
        <threatDefinition id="td00000001">
            <requirements
                elementId="el00000002"
                assetId="al00000001" />
            <threats>
                <threat threatId="tl00000001"
                    severity="3"/>
            </threats>
        </threatDefinition>
    </threatDefinitions>
</definitions>
